

dataset:
  recipe1Msubs_path: Recipe1MSubs_data

ingredients:
  new_gismo_idx2name_filename: new_ingredient_id_to_gismo_name.pickle
  new_gismo_idx2food_on_embeddings_path: ontology_properties/new_ingredient_id_to_foodOn_properties_embeddings
  name2new_gismo_idx_filename: gismo_ingredient_name_to_new_id.pickle
  flavorgraph_embeddings_sub_path: FlavorGraph/FlavorGraph Node Embedding.pickle
  directory: ingredient_vocabularies_and_embeddings
#  vocabulary: flavorgraph
  vocabulary: foodbert
  new_ingredient_id_to_flavorgraph_id: new_ingredient_id_to_flavorgraph_id.pickle
  foodbert_name2index_filename: foodbert_name_to_index.pickle
  foodbert_index2name_filename: foodbert_index_to_name.pickle
  foodbert_embeddings_filename: foodbert_embeddings.pickle

experiment:
#  eval_in_steps: [100, 1000, 10000, -1] #[10, 20] #
  eval_in_steps: [10, 20, 30, 40, 50, 60, 80, 100, 200, 300, 400, 500, 1000, 2000, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, -1] # For first complete draft paper
  num_threads: 8
  eval_on: val
  num_repetitions: 4
  random_seeds: [12, 56, 911, 79, 123, 46, 789, 234, 258, 789]
  save_student_at_steps: [10, 50, 100, 500, 1000, 10000, 49015]
  save_student: False
  student_save_dir: saved_students

teacher:
#  active_learning_method: Balanced
  active_learning_method: Random

student:
#  learning_method: Accumulative
#  learning_method: P_Networks
  learning_method: Baseline
  input_representation:
#    ingredient_representation: 1_hot_embeddings
#    ingredient_representation: 1_hot_embeddings_w_foodOn
#    ingredient_representation: flavorgraph_embed
    ingredient_representation: foodbert_embed
    recipe_ingredient_weights: rarity # 'uniform', 'popularity', 'exp_popularity', 'rarity', 'log_rarity'
    source_ingredient_weight: 9.0 # (float) or 'as_recipe_ingr' the weight of the source ingredient is equal to the total weight of the other recipe ingredients, times the multiplier provided as a parameter
    recipe_ingredient_aggregation: mean # "mean" or 'ignore'
    food_on_hops: 5
    use_food_on_blank_nodes: False

  vector_distance_metric: cosine_distance # l1 or l2 or l4 or sqrt or cosine_distance
